import type { Game, Simulator } from '@/api/api';

/*
 * The catalogue as it was at build time (generated by scripts/snapshot-catalog.mjs; git-ignored).
 * Loaded with import.meta.glob so a missing file — a fresh clone, an offline build — is simply an
 * empty snapshot rather than a build error.
 */

interface Snapshot {
  generatedAt: number;
  games: Game[];
  simulators: Simulator[];
}

const files = import.meta.glob<Snapshot>('../../data/catalog-snapshot.json', { eager: true, import: 'default' });
const loaded = Object.values(files)[0];

export const SNAPSHOT: Snapshot =
  loaded && Array.isArray(loaded.games) && Array.isArray(loaded.simulators)
    ? loaded
    : { generatedAt: 0, games: [], simulators: [] };

/** `initialData` options for a list query: the snapshot, dated honestly so staleness still applies. */
export function snapshotOf(kind: 'games' | 'simulators') {
  const data = SNAPSHOT[kind];
  return data.length > 0 ? { initialData: data, initialDataUpdatedAt: SNAPSHOT.generatedAt } : {};
}
